// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product.Sql.Context;

#nullable disable

namespace Product.Sql.Context.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Product.Sql.Context.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7d2f8cb9-eb2b-407f-88d4-7e55dda8198d"),
                            Description = "Bed description",
                            Name = "Bed",
                            Price = 100m
                        },
                        new
                        {
                            Id = new Guid("b46ac664-5b81-4cd5-b75c-c98fcb4f9e66"),
                            Description = "Tv description",
                            Name = "TV",
                            Price = 50m
                        },
                        new
                        {
                            Id = new Guid("5e2a9604-ad2a-4037-8d32-86c5e170ac7f"),
                            Description = "Chair description",
                            Name = "Chair",
                            Price = 25m
                        },
                        new
                        {
                            Id = new Guid("d3f37fa6-4a7a-407e-953b-71651f937fb8"),
                            Description = "Coffe description",
                            Name = "Coffe",
                            Price = 10m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
