// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using User.Sql.Context;

#nullable disable

namespace User.Sql.Context.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220420201831_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("User.Sql.Context.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("460b92b7-100f-4d96-88f9-4d5e9b2aa996"),
                            Email = "Tim.test@email.com",
                            Name = "Tim",
                            Username = "tim.test"
                        },
                        new
                        {
                            Id = new Guid("e4ecacf2-c3d0-474c-b035-d1c365be0962"),
                            Email = "John.test@email.com",
                            Name = "John",
                            Username = "john.test"
                        },
                        new
                        {
                            Id = new Guid("d5929e69-55ed-4b31-8fe6-5829d0583b8c"),
                            Email = "Jane.test@email.com",
                            Name = "Jane",
                            Username = "jane.test"
                        },
                        new
                        {
                            Id = new Guid("37b118cb-695e-4250-98be-44244c8395ce"),
                            Email = "Doe.test@email.com",
                            Name = "Doe",
                            Username = "doe.test"
                        },
                        new
                        {
                            Id = new Guid("0a5ab071-edff-4462-b15d-44f5269e6271"),
                            Email = "Carl.test@email.com",
                            Name = "Carl",
                            Username = "carl.test"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
